### ISSUE TITLE
Array Out of Bounds Issue in ANS Compressor

### ISSUE THREAD

**Issue by jindajia** [facebookresearch/dietgpu#19]
I am encountering an issue while using the DietGPU library to compress a relatively long array. The floatANS compressor works perfectly, but the ANS compressor is showing an error message: "Check failed: rawSize <= std::numeric_limits<int32_t>::max()".

What is the maximum compressible length of a tensor using the ANS compressor? Is it possible to increase the maximum compression length of the ANS compressor to match that of the floatANS?
<img width="1291" alt="Screenshot 2023-10-22 at 11 52 18 PM" src="https://github.com/facebookresearch/dietgpu/assets/62297091/4c028830-38df-411d-923c-715e2f7d31df">

**Comment by wickedfoo** [comment]
Both the ANS codec and the floating point codec are written using 32-bit indexing arithmetic, because the original target for dietgpu was super high performance compression/decompression for InfiniBand / fast Ethernet communications during large-scale neural network training, as there are sometimes severe penalties for 64-bit integer/pointer arithmetic on Nvidia GPUs. In this use case, we are typically transferring 100s of kB to 100s of MB of data between machines/GPUs, not much more. 

I won't update the code here to use 64-bit indexing instead, but you can bypass the problem by separately compressing chunks of the input to get under the (2^31 - 1) limit that this is complaining about and append them together if you need to be able to compress and decompress longer runs of data.

**Comment by wickedfoo** [comment]
Both the ANS codec and the floating point codec are written using 32-bit indexing arithmetic, because the original target for dietgpu was super high performance compression/decompression for InfiniBand / fast Ethernet communications during large-scale neural network training, as there are sometimes severe penalties for 64-bit integer/pointer arithmetic on Nvidia GPUs. In this use case, we are typically transferring 100s of kB to 100s of MB of data between machines/GPUs and targeting compression speeds in the 100s of GB per second, not compressing much larger pieces of data.

I won't update the code here to use 64-bit indexing instead, but you can bypass the problem by separately compressing chunks of the input to get under the (2^31 - 1) limit that this is complaining about and append them together if you need to be able to compress and decompress longer runs of data.

**Comment by wickedfoo** [comment]
Both the ANS codec and the floating point codec are written using 32-bit indexing arithmetic, because the original target for dietgpu was super high performance compression/decompression for InfiniBand / fast Ethernet communications during large-scale neural network training, as there are sometimes severe penalties for 64-bit integer/pointer arithmetic on Nvidia GPUs. In this use case, we are typically transferring 100s of kB to 100s of MB of data between machines/GPUs and targeting compression speeds in the 100s of GB per second, not compressing much larger pieces of data.

I won't update the code here to use 64-bit indexing instead, but you can bypass the problem by separately compressing chunks of the input to get under the (2^31 - 1) limit that this is complaining about and append them together if you need to be able to compress and decompress longer runs of data.

**Comment by jindajia** [comment]
Cool! Thank you for your response.
